version: '3.8'

services:
  dashboard:
    build: .
    image: github-dashboard:latest
    container_name: github-dashboard
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8080}:${CONTAINER_PORT:-8000}"
    environment:
      - REPOS=${REPOS}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REFRESH_SECONDS=${REFRESH_SECONDS:-60}
      # Pass the new variable
      - REPO_UPDATE_INTERVAL_SECONDS=${REPO_UPDATE_INTERVAL_SECONDS:-10}
      - PORT=${CONTAINER_PORT:-8000}
      - TZ=${TZ:-UTC}